### ISSUE TITLE
Placeholder quotes

### ISSUE THREAD

**Issue by jmaldia** [chingu-voyage5/Geckos-Team-0#24]
child of #20

**Comment by jmaldia** [comment]
http://screen.ac/1x3T1z0F1p0j

**Comment by NariRoh** [comment]
![Screen Shot 2018-06-10 at 8.30.26 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5afc9ab2840a8400138accac/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77256455f36b7191a370f1112b4f5d595ecc3c4a4356bcbbd671f3e57862804e0ebfd06d5c20c46e47acba854bbd01ba21d81d83b2b8d94dd2f42f67b6d5db1063474f4dcbed5727a19041c95df443e74555a21a366be3732431.png)

Do we want to implement this feature as well? 
When hovering over the quote, 
- It shows an author of the quote
- A heart button (I don't know exactly what this does other than making the heart fully white
- A Twitter icon (to share on twitter)

**Comment by jmaldia** [comment]
Sure. We can add that to the backlog. Add it as a child of the main card for that feature. Not this one.

**Comment by NariRoh** [comment]
Okieee!
